export const SET_TIMER_VALUE = 'SET_TIMER_VALUE';
export const SET_KEY_VALUE = 'SET_KEY_VALUE';
export const SET_BRUSH_COLOR = 'SET_BRUSH_COLOR';
export const SET_DRAWING_ENABLED = 'SET_DRAWING_ENABLED';
export const SET_PAINTING = 'SET_PAINTING';
export const SET_RADIUS_MODIFIER = 'SET_RADIUS_MODIFIER';
export const SET_RADIUS = 'SET_RADIUS';
export const SET_CURRENT_LINE = 'SET_CURRENT_LINE';
