// @flow
export const SET_TIMER_VALUE = 'SET_TIMER_VALUE';
export const SET_KEY_VALUE = 'SET_KEY_VALUE';
export const SET_BRUSH_COLOR = 'SET_BRUSH_COLOR';
export const SET_DRAWING_ENABLED = 'SET_DRAWING_ENABLED';
export const SET_PAINTING = 'SET_PAINTING';
export const SET_RADIUS_MODIFIER = 'SET_RADIUS_MODIFIER';
export const SET_RADIUS = 'SET_RADIUS';
export const APPEND_TO_CURRENT_LINE = 'APPEND_TO_CURRENT_LINE';
export const SET_CURRENT_LINE = 'SET_CURRENT_LINE';
export const REMOVE_LINE_WITH_KEY = 'REMOVE_LINE_WITH_KEY';
export const APPEND_TO_DRAWING_OBJECT = 'APPEND_TO_DRAWING_OBJECT';
export const APPEND_TO_END_OF_LINE_WITH_KEY = 'APPEND_TO_END_OF_LINE_WITH_KEY';
export const NEW_DRAWING_OBJECT = 'NEW_DRAWING_OBJECT';
